### ISSUE TITLE
Tone Analyzer: Invalid JSON input

### ISSUE THREAD

**Issue by nguyendn** [watson-developer-cloud/ruby-sdk#107]
**Describe the bug**
Can not call Tone Analyzer API

**To Reproduce**

```ruby
authenticator = IBMWatson::Authenticators::IamAuthenticator.new(apikey: "API KEY")
service = IBMWatson::ToneAnalyzerV3.new(version: "2017-09-21", authenticator: authenticator)
service.service_url = "https://api.us-south.tone-analyzer.watson.cloud.ibm.com/instances/<some_id>/v3/tone_chat?version=2017-09-21"
text = "Team, I know that times are tough! Product sales have been disappointing for the past three quarters. We have a competitive product, but we need to do a better job of selling it!"
tone = service.tone( tone_input: {text: text},  content_type: "application/json")
```
**Expected behavior**
Can call API successfully

**Actual behavior**
```
IBMCloudSdkCore::ApiException (Error: Invalid JSON input at line 1, column 10, Code: 400, Information: {"sub_code"=>"C00012"}, X-dp-watson-tran-id: 9d10aa5e-888a-4a0f-b2f9-688a2d51abf6, X-global-transaction-id: 9d10aa5e-888a-4a0f-b2f9-688a2d51abf6)
```
**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Ruby Version: ruby-2.6.6

** Additional Context**
1. I follow the document here https://cloud.ibm.com/apidocs/tone-analyzer?code=ruby#sync and here https://github.com/watson-developer-cloud/ruby-sdk/blob/master/examples/tone_analyzer_v3.rb
2. It seems API doesn't support "text/plain" anymore also.

**Comment by Mikemosca** [comment]
"text/plain" works fine for me.  The error above is caused because you did not pass a valid json string and specified 
"application/json")

In you example you take a text string and pass it into tone as json.  This also worked fine for me.

text = "Team, I know that times are tough! Product sales have been disappointing for the past three quarters. We have a competitive product, but we need to do a better job of selling it!"
tone = service.tone( tone_input: {text: text},  content_type: "application/json")

You could also do something like this and use plain text
text = "Team, I know that times are tough! Product sales have been disappointing for the past three quarters. We have a competitive product, but we need to do a better job of selling it!"
tone = service.tone( tone_input: text,  content_type: "text/plain")
